services:
  mainnode:
    image: akka.cluster.streamingstatus:latest
    hostname: streaming.main
    ports:
      - '9110:9110'
      - '8080:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AkkaSettings__RemoteOptions__Port: 4055
      AkkaSettings__RemoteOptions__Hostname: "streaming.main"
      AkkaSettings__ClusterOptions__SeedNodes__0: "akka.tcp://ClusterSys@streaming.main:4055"

  streaming:
    image: akka.cluster.streamingstatus:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AkkaSettings__RemoteOptions__Port: 4055
      AkkaSettings__ClusterOptions__SeedNodes__0: "akka.tcp://ClusterSys@streaming.main:4055"
    depends_on:
      - "mainnode"